const actionTypes = {
  ADD_PRODUCER: 'ADD_PRODUCER',

  ADD_PRODUCT: 'ADD_PRODUCT',
  SELL_PRODUCT: 'SELL_PRODUCT',
  PRODUCE_PRODUCTS: 'PRODUCE_PRODUCTS',

  OPEN_STORE: 'OPEN_STORE',
};

export default actionTypes;
