const actionTypes = {
  ADD_PRODUCER: 'ADD_PRODUCER',
  ADD_SELLER: 'ADD_SELLER',

  ADD_PRODUCT: 'ADD_PRODUCT',
  SELL_PRODUCT: 'SELL_PRODUCT',

  OPEN_STORE: 'OPEN_STORE',
  CLOSE_STORE: 'CLOSE_STORE',
};

export default actionTypes;
