const sellers = {
  FOR_SALE_SIGN: 'FOR_SALE_SIGN',
  NEWSPAPER_AD: 'NEWSPAPER_AD',
  SHOPKEEPER: 'SHOPKEEPER',
  CHICKEN_DEALER: 'CHICKEN_DEALER',
  CRAIGSLIST_AD: 'CRAIGSLIST_AD',
};

export default sellers;
